FROM python:3.8.7-slim-buster

WORKDIR /app

# copy dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt 

COPY src/ .

# Set environment variables
ENV FLASK_APP=app.py
ENV FLASK_ENV=production
EXPOSE 8000

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "app:app"]