"""Add created_at time to the tables and alter password tto password hash

Revision ID: 2c0c75619435
Revises: 1b0cc382c052
Create Date: 2025-02-09 15:42:08.651833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c0c75619435'
down_revision: Union[str, None] = '1b0cc382c052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(length=300), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'password_hash')
    op.drop_column('tasks', 'created_at')
    # ### end Alembic commands ###
