"""add partial index to Task.done and add user email

Revision ID: 574b9b8bb688
Revises: 85198b79fc15
Create Date: 2025-02-11 15:24:03.117773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '574b9b8bb688'
down_revision: Union[str, None] = '85198b79fc15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('done_equals_false', 'tasks', ['done'], unique=False, postgresql_where=sa.text('done = false'))
    op.add_column('users', sa.Column('email', sa.String(length=30), nullable=False, server_default='adeyinkaadegbenro@gmail.com'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_index('done_equals_false', table_name='tasks', postgresql_where=sa.text('done = false'))
    # ### end Alembic commands ###
